---
route:
  receiver: slack
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  routes:
    - match:
        severity: critical
      receiver: slack-critical
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: slack-warning
      repeat_interval: 2h

receivers:
  - name: slack
    slack_configs:
      - api_url_file: /etc/alertmanager/secrets/slack_webhook_url
        send_resolved: true
        title: >-
          [{{ .Status | toUpper }}] {{ or .CommonAnnotations.summary .CommonLabels.alertname }}
        text: >-
          {{ or .CommonAnnotations.description .CommonAnnotations.message "No description" }}

  - name: slack-critical
    slack_configs:
      - api_url_file: /etc/alertmanager/secrets/slack_webhook_url
        send_resolved: true
        title: >-
          ðŸš¨ [CRITICAL] {{ or .CommonAnnotations.summary .CommonLabels.alertname }}
        text: >-
          {{ or .CommonAnnotations.description .CommonAnnotations.message "No description" }}

  - name: slack-warning
    slack_configs:
      - api_url_file: /etc/alertmanager/secrets/slack_webhook_url
        send_resolved: true
        title: >-
          âš ï¸ [WARNING] {{ or .CommonAnnotations.summary .CommonLabels.alertname }}
        text: >-
          {{ or .CommonAnnotations.description .CommonAnnotations.message "No description" }}
